// Builds openapi.json, the contract the web app's types are generated from:
//
//   api.openapi.json      generated from the API's route schemas (the source of truth)
// + planned.openapi.json  hand-written endpoints the web app is built against that the API does
//                         not implement yet
// = openapi.json
//
// The API always wins. A planned path or schema that the API now generates is an error: delete it
// from planned.openapi.json, so there is exactly one definition of everything.
import { readFileSync, writeFileSync } from 'node:fs';

const read = (file) => JSON.parse(readFileSync(new URL(`../${file}`, import.meta.url), 'utf8'));

export function mergeSpecs(api, planned) {
  const problems = [];
  const merged = structuredClone(api);
  merged.paths ??= {};
  merged.components ??= {};

  for (const [path, item] of Object.entries(planned.paths ?? {})) {
    if (path in merged.paths) {
      problems.push(
        `Path ${path} is now generated by the API. Remove it from planned.openapi.json.`,
      );
      continue;
    }
    // Marked so tools and readers can tell what is real.
    merged.paths[path] = Object.fromEntries(
      Object.entries(item).map(([method, operation]) => [
        method,
        typeof operation === 'object' && operation !== null && !Array.isArray(operation)
          ? { ...operation, 'x-planned': true }
          : operation,
      ]),
    );
  }

  for (const [section, entries] of Object.entries(planned.components ?? {})) {
    merged.components[section] ??= {};
    for (const [name, value] of Object.entries(entries)) {
      if (name in merged.components[section]) {
        problems.push(
          `components.${section}.${name} is now generated by the API. Remove it from planned.openapi.json.`,
        );
        continue;
      }
      merged.components[section][name] = value;
    }
  }

  // Every reference must point at something, whichever file it came from.
  const text = JSON.stringify(merged);
  for (const [, section, name] of text.matchAll(/"#\/components\/(\w+)\/([^"/]+)"/g)) {
    if (!(name in (merged.components[section] ?? {}))) {
      problems.push(`Reference to missing components.${section}.${name}.`);
    }
  }

  if (problems.length > 0) {
    throw new Error(`Cannot build the contract:\n- ${[...new Set(problems)].join('\n- ')}`);
  }
  return merged;
}

// Run as a script (not when imported by its test).
if (
  process.argv[1] &&
  import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/').split('/').pop())
) {
  const merged = mergeSpecs(read('api.openapi.json'), read('planned.openapi.json'));
  writeFileSync(
    new URL('../openapi.json', import.meta.url),
    `${JSON.stringify(merged, null, 2)}\n`,
  );
  const planned = Object.values(merged.paths).filter((item) =>
    Object.values(item).some((operation) => operation?.['x-planned']),
  ).length;
  console.log(
    `openapi.json: ${Object.keys(merged.paths).length} paths (${planned} planned, not yet in the API).`,
  );
}
