// End-to-end hospital modules added to the core roadmap. Assembled and renumbered by roadmap.mjs.
// Task and acceptance lists are semicolon-separated strings (keep semicolons out of the text).

const L = (s) =>
  s
    ? s
        .split(';')
        .map((x) => x.trim())
        .filter(Boolean)
    : [];
const I = (id, title, area, pri, size, deps, tasks, ac, extra = {}) => ({
  id,
  title,
  area,
  pri,
  size,
  deps: deps ? deps.split(' ') : [],
  tasks: L(tasks),
  ac: L(ac),
  ...extra,
});

// New milestones (keys are placeholders, final numbers are assigned in roadmap.mjs).
export const extraMilestones = [
  {
    key: 'MD',
    name: 'Master data and catalogs',
    weeks: 3,
    release: 'R1',
    goal: 'Catalogs every other module depends on: services and prices, drugs, lab tests, codes, wards and beds, templates, and bulk import.',
    exit: 'A hospital admin can load and maintain its catalogs, prices are effective-dated, and other modules can reference them by ID.',
    refs: 'Product Scope (Master data first), Domain Types',
    issues: [
      I(
        'MD-01',
        'Service and tariff catalog with price lists',
        'frontend',
        'P0',
        'M',
        'F-08 BE-05',
        'Services (consultation, procedure, bed, lab, imaging, package) with codes, categories and tax class; Price lists per hospital with effective dates and category pricing; Archive instead of delete',
        'Price changes never alter issued invoices; Prices are versioned',
      ),
      I(
        'MD-02',
        'Drug and consumable master',
        'frontend',
        'P0',
        'M',
        'MD-01',
        'Generic and brand names, form, strength, unit, drug schedule and controlled flag, tax, reorder level; Server-side search; Duplicate detection',
        'Search returns in under a second on 50k items',
      ),
      I(
        'MD-03',
        'Lab test catalog and reference ranges',
        'frontend',
        'P0',
        'M',
        'MD-01',
        'Tests and panels, sample type and container, turnaround time, units; Reference ranges by age and sex; Link each test to a service price',
        'Ranges resolve correctly for a given patient age and sex',
      ),
      I(
        'MD-04',
        'Wards, rooms and bed setup',
        'frontend',
        'P1',
        'M',
        'MD-01',
        'Wards, room categories, beds and their tariffs; Bed status model (available, occupied, cleaning, blocked)',
        'Bed categories link to bed-day charges',
      ),
      I(
        'MD-05',
        'Diagnosis and procedure code search',
        'frontend',
        'P1',
        'S',
        'MD-01',
        'ICD-10 and procedure code typeahead through the server, never bundled; Per-hospital favourites',
        'Searching a large code set does not increase bundle size',
      ),
      I(
        'MD-06',
        'Document and clinical templates',
        'frontend',
        'P2',
        'S',
        'MD-01',
        'Versioned templates for prescriptions, clinical notes, consent forms and discharge summaries; Variable placeholders; Preview',
        'Templates are versioned and tenant-specific',
      ),
      I(
        'MD-07',
        'Bulk import centre (patients, staff, catalogs)',
        'frontend',
        'P1',
        'M',
        'MD-01 MD-02 MD-03',
        'CSV upload with column mapping, validation, dry run and error report; Run as a background job with progress; Rollback of a failed batch; Patient import restricted and audited',
        'A 10k-row import completes without blocking the UI',
      ),
      I(
        'BE-17',
        'Master data API',
        'backend',
        'P0',
        'L',
        'BE-05',
        'Tables with tenant_id and RLS; Platform-seeded defaults (ICD-10, standard tests and drugs) with tenant overlays; Effective-dated prices; Trigram search endpoints; Import jobs on the queue; Events master.changed',
        'RLS tests pass; Historic prices are retrievable by date',
      ),
    ],
  },
  {
    key: 'LAB',
    name: 'Laboratory',
    weeks: 3,
    release: 'R1',
    goal: 'Lab workflow from order to verified report.',
    exit: 'Lab orders flow through sample collection, result entry and verification, and the doctor sees verified results with critical values acknowledged.',
    refs: 'Product Scope (unified orders), Domain Types',
    issues: [
      I(
        'LB-01',
        'Lab worklist and sample collection',
        'frontend',
        'P0',
        'M',
        'C-03 MD-03',
        'Worklist by status and priority; Sample collection with accession ID and printable barcode label; Reject and recollect with reason',
        'Every sample has a unique accession ID',
      ),
      I(
        'LB-02',
        'Result entry and verification',
        'frontend',
        'P0',
        'L',
        'LB-01',
        'Result entry per test with units and reference ranges; Abnormal and critical flags; Technician enters and pathologist verifies; Amendments keep history',
        'Unverified results are never visible to doctors as final',
      ),
      I(
        'LB-03',
        'Lab reports and result viewing',
        'frontend',
        'P0',
        'M',
        'LB-02',
        'Printable report with hospital letterhead; Results shown in the consultation and timeline; Critical value acknowledgement by the doctor; Trend of one test over time',
        'Critical values require acknowledgement',
      ),
      I(
        'LB-04',
        'Laboratory tests and end-to-end flow',
        'frontend',
        'P0',
        'S',
        'LB-03',
        'Unit tests for result entry and flags; Playwright: order, collect, result, verify, view',
        'E2E passes in CI',
      ),
      I(
        'LB-05',
        'Outsourced tests tracking',
        'frontend',
        'P2',
        'S',
        'LB-02',
        'Mark tests as outsourced with partner lab; Track sent and received',
        'Outsourced results can be attached and verified',
      ),
      I(
        'BE-19',
        'Laboratory API',
        'backend',
        'P0',
        'L',
        'BE-12 BE-17',
        'lab_samples and lab_results; State machine ordered, collected, received, resulted, verified; Reference range evaluation; Versioned amendments; Events lab.sample_collected, lab.result_verified, lab.critical_value; Audit',
        'Invalid transitions are rejected; RLS tests pass',
      ),
    ],
  },
  {
    key: 'RAD',
    name: 'Radiology and imaging',
    weeks: 2,
    release: 'R1',
    goal: 'Imaging orders, scheduling and reporting.',
    exit: 'Imaging orders are performed and reported, and doctors see signed-off reports.',
    refs: 'Product Scope (unified orders)',
    issues: [
      I(
        'RD-01',
        'Imaging worklist and scheduling',
        'frontend',
        'P1',
        'M',
        'C-07',
        'Worklist by modality and status; Schedule a slot; Status flow ordered, scheduled, performed, reported',
        'Status transitions validated by tests',
      ),
      I(
        'RD-02',
        'Imaging report entry and sign-off',
        'frontend',
        'P1',
        'M',
        'RD-01',
        'Structured report templates; Radiologist sign-off; Attach image files or external links through signed URLs (no DICOM viewer in this release); Amendments keep history',
        'Signed reports are immutable with addenda',
      ),
      I(
        'RD-03',
        'Radiology tests and end-to-end flow',
        'frontend',
        'P1',
        'S',
        'RD-02',
        'Unit tests; Playwright: order, perform, report, view',
        'E2E passes in CI',
      ),
      I(
        'BE-20',
        'Radiology API',
        'backend',
        'P1',
        'M',
        'BE-12',
        'imaging_orders and reports; Signed-URL uploads with size and type limits and a malware scan job; Events imaging.reported',
        'Uploads rejected when over limits; RLS tests pass',
      ),
    ],
  },
  {
    key: 'PHX',
    name: 'Pharmacy and inventory',
    weeks: 4,
    release: 'R1',
    goal: 'Dispense medicines safely and manage stock, batches, expiry and purchasing.',
    exit: 'Prescriptions are dispensed with correct batches, stock stays accurate under concurrency, and purchasing and goods receipt work.',
    refs: 'Product Scope (append-only ledgers), Domain Types',
    issues: [
      I(
        'PH-01',
        'Prescription queue and dispensing',
        'frontend',
        'P0',
        'L',
        'C-02 MD-02',
        'Queue of prescriptions; Full and partial dispense with batch and expiry selection (nearest expiry first); Generic substitution; Allergy warning from the patient record; Dispense slip print',
        'Dispensing reduces stock exactly once, even on retry',
      ),
      I(
        'PH-02',
        'Counter sales and controlled drug register',
        'frontend',
        'P1',
        'M',
        'PH-01',
        'Sale without prescription for allowed items; Controlled and scheduled drug register entries; Sale returns',
        'Controlled drug sales always create register entries',
      ),
      I(
        'PH-03',
        'Stock, batches and expiry',
        'frontend',
        'P0',
        'M',
        'MD-02',
        'Stock by item, batch and location; Expiry and low-stock alerts; Stock adjustments with reason and approval; Stock ledger view',
        'Every stock change appears in the ledger',
      ),
      I(
        'PH-04',
        'Suppliers, purchase orders and goods receipt',
        'frontend',
        'P1',
        'L',
        'PH-03',
        'Suppliers; Purchase order create and approve; Goods receipt with batch, expiry and cost; Purchase returns',
        'Receipt adds batches and ledger entries',
      ),
      I(
        'PH-05',
        'Pharmacy returns and wastage',
        'frontend',
        'P1',
        'S',
        'PH-01',
        'Return to stock and expiry write-off with reason and approval',
        'Returns respect the original dispense',
      ),
      I(
        'PH-06',
        'Store indents and issue',
        'frontend',
        'P2',
        'M',
        'PH-03',
        'Department and ward indents to the main store; Approve and issue vouchers',
        'Indents reconcile with stock issued',
      ),
      I(
        'PH-07',
        'Pharmacy tests and end-to-end flow',
        'frontend',
        'P0',
        'S',
        'PH-04',
        'Unit tests; Playwright: prescription, dispense, stock check, purchase, receipt',
        'E2E passes in CI',
      ),
      I(
        'BE-21',
        'Pharmacy and inventory API',
        'backend',
        'P0',
        'L',
        'BE-12 BE-17',
        'items, batches, stock_ledger (append-only), dispenses and indents; Concurrency-safe stock decrement with row locks; Batch selection by expiry; Controlled drug register; Idempotent dispense; Events pharmacy.dispensed, stock.low, stock.expiring',
        'Concurrent dispenses never oversell; RLS tests pass',
      ),
      I(
        'BE-22',
        'Purchasing API',
        'backend',
        'P1',
        'L',
        'BE-21',
        'suppliers, purchase_orders, goods_receipts and returns; Approval workflow by permission; Costing method documented; Audit',
        'Goods receipt is idempotent',
      ),
    ],
  },
  {
    key: 'IPD',
    name: 'Bed management and admissions',
    weeks: 3,
    release: 'R2',
    goal: 'Admit, track and move inpatients with an accurate live bed board.',
    exit: 'Patients can be admitted into beds, transferred and tracked, and double occupancy is impossible.',
    refs: 'Product Scope (IPD journey), Domain Types',
    issues: [
      I(
        'IP-01',
        'Bed board and ward map',
        'frontend',
        'P0',
        'L',
        'MD-04',
        'Live bed board by ward and status with filters; Mark cleaning, blocked and ready; Live updates through server-sent events',
        'Updates appear for other users within seconds',
      ),
      I(
        'IP-02',
        'Admission workflow',
        'frontend',
        'P0',
        'L',
        'IP-01 C-01',
        'Admission advice from the doctor; Admit from OPD, emergency or directly; Choose bed by category and tariff; Attendant details, deposit and consents; Assign the primary doctor; Creates an inpatient encounter',
        'Admitting without an available bed is blocked',
      ),
      I(
        'IP-03',
        'Transfers and bed changes',
        'frontend',
        'P1',
        'M',
        'IP-02',
        'Ward and bed transfer with reason; Bed history; Tariff change handling for bed charges',
        'Bed history is complete and charges split correctly',
      ),
      I(
        'IP-04',
        'Inpatient census and admitted list',
        'frontend',
        'P1',
        'S',
        'IP-02',
        'Admitted patients by ward and doctor; Expected discharges; Occupancy summary',
        'Census matches the bed board',
      ),
      I(
        'IP-05',
        'Admissions tests and end-to-end flow',
        'frontend',
        'P0',
        'S',
        'IP-03',
        'Unit tests; Playwright: admit, transfer, view board; Two-tenant isolation',
        'E2E passes in CI',
      ),
      I(
        'BE-23',
        'Admission, discharge and transfer (ADT) API',
        'backend',
        'P0',
        'L',
        'BE-12 BE-17',
        'admissions and bed_assignments with history; Exclusion constraint prevents double occupancy; SSE stream for the bed board; Events admission.created, bed.assigned, bed.released',
        'Concurrent admissions to one bed cannot both succeed',
      ),
    ],
  },
  {
    key: 'NUR',
    name: 'Nursing and ward care',
    weeks: 3,
    release: 'R2',
    goal: 'Bedside care: vitals, medication administration, rounds, notes and diet.',
    exit: 'Nurses and doctors can run daily ward care with a complete, append-only record.',
    refs: 'Product Scope (append-only records), Domain Types',
    issues: [
      I(
        'NR-01',
        'Nursing worklist and vitals charting',
        'frontend',
        'P0',
        'M',
        'IP-02',
        'Patient list per ward and nurse; Periodic vitals with trend chart; Configurable early warning score',
        'Abnormal trends are highlighted',
      ),
      I(
        'NR-02',
        'Medication orders and administration record (MAR)',
        'frontend',
        'P0',
        'L',
        'IP-02 C-07',
        'Inpatient medication orders with a schedule; Nurse records administration with dose checks; Held and missed doses with reason; Allergy checks',
        'Administration entries cannot be edited, only amended with a new entry',
      ),
      I(
        'NR-03',
        'Doctor rounds and progress notes',
        'frontend',
        'P0',
        'M',
        'IP-02',
        'Round list per doctor; Daily progress notes with versioned amendments; Place orders from the ward',
        'Notes keep full amendment history',
      ),
      I(
        'NR-04',
        'Nursing notes, intake and output, care plans',
        'frontend',
        'P1',
        'M',
        'NR-01',
        'Shift notes; Fluid intake and output totals; Care plans with tasks',
        'Totals are calculated per shift',
      ),
      I(
        'NR-05',
        'Diet orders and kitchen list',
        'frontend',
        'P2',
        'S',
        'IP-02',
        'Diet types per patient; Daily kitchen list by ward',
        'Kitchen list reflects the latest orders',
      ),
      I(
        'NR-06',
        'Ward care tests and end-to-end flow',
        'frontend',
        'P0',
        'S',
        'NR-03',
        'Unit tests; Playwright: vitals, order, administer, round note',
        'E2E passes in CI',
      ),
      I(
        'BE-24',
        'Nursing and ward care API',
        'backend',
        'P0',
        'L',
        'BE-23',
        'vitals series, mar_entries (append-only), progress_notes with history, diet orders; Ward stock indent hook; Event medication.administered',
        'Append-only enforced at database level; RLS tests pass',
      ),
    ],
  },
  {
    key: 'DIS',
    name: 'Discharge and inpatient billing',
    weeks: 3,
    release: 'R2',
    goal: 'Controlled discharge with a correct running and final bill.',
    exit: 'A patient can be discharged only after clearances, with a signed summary and a settled final bill.',
    refs: 'Product Scope (charge ledger), Domain Types',
    issues: [
      I(
        'DS-01',
        'Discharge planning and clearances',
        'frontend',
        'P0',
        'L',
        'NR-03',
        'Discharge advice; Clearance checklist (nursing, pharmacy returns, pending lab, billing); Types normal, LAMA, referral and death; Bed released to cleaning',
        'Discharge is blocked until required clearances are done',
      ),
      I(
        'DS-02',
        'Discharge summary',
        'frontend',
        'P0',
        'M',
        'DS-01 MD-05',
        'Template-based summary with diagnoses, procedures, course, results, medicines and follow-up; Doctor sign-off; Print view',
        'Signed summaries are immutable with addenda',
      ),
      I(
        'DS-03',
        'Running inpatient bill and deposits',
        'frontend',
        'P0',
        'L',
        'B-06 IP-02',
        'Daily bed charges accrue by category; Services, medicines, lab and procedures captured as charges; Deposits and interim bills; Estimate versus actual',
        'Running bill matches the charge ledger',
      ),
      I(
        'DS-04',
        'Final bill and settlement',
        'frontend',
        'P0',
        'M',
        'DS-03',
        'Final bill, refund of excess deposit, credit notes; Payment modes; Discharge gating by policy',
        'Final bill totals equal the sum of charges',
      ),
      I(
        'DS-05',
        'Discharge tests and end-to-end flow',
        'frontend',
        'P0',
        'S',
        'DS-04',
        'Unit tests; Playwright: clear, summarize, bill, discharge',
        'E2E passes in CI',
      ),
      I(
        'BE-25',
        'Discharge and inpatient billing API',
        'backend',
        'P0',
        'L',
        'BE-23 BE-13',
        'Discharge state machine with clearances; Daily bed-charge job that is idempotent per tenant and day; Deposits ledger; Immutable signed summaries; Event discharge.completed',
        'Running the daily job twice posts charges once',
      ),
      I(
        'DS-06',
        'Release R2 hardening',
        'security',
        'P0',
        'M',
        'DS-05',
        'Performance and load test with inpatient data; Security and tenant isolation review of new modules; Full journey regression OPD and IPD; Update runbooks',
        'Checklist signed off',
      ),
    ],
  },
  {
    key: 'ER',
    name: 'Emergency',
    weeks: 2,
    release: 'R3',
    goal: 'Emergency registration, triage, rapid care and disposition.',
    exit: 'Emergency patients can be registered quickly (even unidentified), triaged, treated and admitted or discharged.',
    refs: 'Product Scope (Emergency journey)',
    issues: [
      I(
        'ER-01',
        'Emergency registration and triage board',
        'frontend',
        'P0',
        'M',
        'P-02 Q-02',
        'Quick registration including unidentified patients with a temporary ID; Triage category (1 to 5) with timers; Live tracking board',
        'A patient can be registered in under 30 seconds',
      ),
      I(
        'ER-02',
        'Emergency care and disposition',
        'frontend',
        'P0',
        'M',
        'ER-01 IP-02',
        'Rapid orders and observation notes; Disposition discharge, admit, refer or expired; Admit creates the inpatient encounter',
        'Admission from the emergency department preserves history',
      ),
      I(
        'ER-03',
        'Medico-legal case records',
        'frontend',
        'P1',
        'S',
        'ER-01',
        'Flag medico-legal cases; Required fields and restricted access; Audit on every view',
        'Access limited to permitted roles',
      ),
      I(
        'ER-04',
        'Emergency tests and end-to-end flow',
        'frontend',
        'P1',
        'S',
        'ER-02',
        'Unit tests; Playwright: register, triage, treat, admit',
        'E2E passes in CI',
      ),
      I(
        'BE-26',
        'Emergency API',
        'backend',
        'P0',
        'M',
        'BE-12 BE-23',
        'er_encounters; Temporary identity and merge into a real patient with audit; Events er.triaged',
        'Merge is reversible within a window and fully audited',
      ),
    ],
  },
  {
    key: 'OT',
    name: 'Operation theatre',
    weeks: 3,
    release: 'R3',
    goal: 'Surgery scheduling, safety checklists, operation records and charges.',
    exit: 'Surgeries can be booked without conflicts, documented, and billed with consumables.',
    refs: 'Product Scope (Surgery journey)',
    issues: [
      I(
        'OT-01',
        'OT scheduling and theatre calendar',
        'frontend',
        'P0',
        'L',
        'IP-02 D-02',
        'Theatres, surgeons, anaesthetists and team; Booking with conflict detection for theatre and surgeon; Status flow',
        'Conflicts are rejected by the server',
      ),
      I(
        'OT-02',
        'Pre-operative checklist and anaesthesia record',
        'frontend',
        'P1',
        'M',
        'OT-01 MD-06',
        'Consent and fitness; Surgical safety checklist steps recorded with times; Anaesthesia record',
        'Checklist steps are timestamped and signed',
      ),
      I(
        'OT-03',
        'Operation note, consumables and procedure charges',
        'frontend',
        'P0',
        'M',
        'OT-01 PH-03',
        'Operative notes; Implants and consumables used from stock; Procedure charges and packages posted to the bill',
        'Consumables reduce stock and post charges',
      ),
      I(
        'OT-04',
        'Post-operative care and OT tests',
        'frontend',
        'P1',
        'S',
        'OT-03',
        'Recovery notes and orders; Unit and Playwright tests',
        'E2E passes in CI',
      ),
      I(
        'BE-27',
        'Operation theatre API',
        'backend',
        'P0',
        'L',
        'BE-23 BE-21',
        'ot_bookings with exclusion constraints for theatre and surgeon; Consumable usage deducts stock; Event surgery.completed',
        'Concurrent bookings cannot overlap',
      ),
    ],
  },
  {
    key: 'INS',
    name: 'Insurance, TPA and claims',
    weeks: 4,
    release: 'R3',
    goal: 'Cashless and claim workflows with split billing and receivables.',
    exit: 'Insured admissions can be pre-authorized, billed with a payer split, claimed and settled.',
    refs: 'Product Scope (Insured patients), Domain Types',
    issues: [
      I(
        'IN-01',
        'Insurer, TPA and corporate masters',
        'frontend',
        'P0',
        'M',
        'MD-01',
        'Insurers, TPAs and corporates; Plans, covered services, rate agreements and eligibility rules',
        'Rate agreements are effective-dated',
      ),
      I(
        'IN-02',
        'Policy capture and pre-authorization',
        'frontend',
        'P0',
        'L',
        'IN-01 IP-02',
        'Policy details at registration and admission; Pre-authorization request with documents and status; Alerts when the bill nears the approved limit',
        'Pre-auth limits are visible during admission billing',
      ),
      I(
        'IN-03',
        'Split billing and co-pay',
        'frontend',
        'P0',
        'L',
        'IN-02 DS-04',
        'Split invoice between patient and payer; Co-pay and non-payable items; Payer-specific rates',
        'Split totals always reconcile with the charge ledger',
      ),
      I(
        'IN-04',
        'Claims submission and tracking',
        'frontend',
        'P0',
        'L',
        'IN-03',
        'Claim packet with documents; Submit, query and reply, settlement; Short-payment write-off; Aging view',
        'Claim states follow the allowed transitions',
      ),
      I(
        'IN-05',
        'Corporate credit billing and receivables',
        'frontend',
        'P1',
        'M',
        'IN-03',
        'Credit billing to corporates; Receivable statements and receipts',
        'Receivables reconcile with payments',
      ),
      I(
        'IN-06',
        'Insurance tests and end-to-end flow',
        'frontend',
        'P1',
        'S',
        'IN-04',
        'Unit tests; Playwright: policy, pre-auth, split bill, claim',
        'E2E passes in CI',
      ),
      I(
        'BE-28',
        'Insurance and claims API',
        'backend',
        'P0',
        'L',
        'BE-25',
        'Insurer, policy, pre-auth and claim tables; Claim state machine; Document attachments; Receivables ledger; Export adapters for payer formats; Events claim.submitted and claim.settled',
        'RLS tests pass; Invalid claim transitions rejected',
      ),
      I(
        'IN-07',
        'Release R3 hardening',
        'security',
        'P0',
        'M',
        'IN-06 ER-04 OT-04',
        'Performance and load tests; Security review; Full journey regression including emergency, surgery and insurance',
        'Checklist signed off',
      ),
    ],
  },
  {
    key: 'MRD',
    name: 'Medical records and documents',
    weeks: 2,
    release: 'R4',
    goal: 'Document storage, consents, certificates and record quality.',
    exit: 'Hospitals can store records, capture consents, issue certificates, and merge duplicate patients safely.',
    refs: 'Product Scope, Security and Privacy',
    issues: [
      I(
        'MR-01',
        'Patient document store',
        'frontend',
        'P1',
        'M',
        'P-03',
        'Upload scanned reports and outside records; Types and tags; Signed URL access; Size and type limits; Audit on every view; Patient tab through the slot',
        'Every document view is audited',
      ),
      I(
        'MR-02',
        'Consents and certificates',
        'frontend',
        'P1',
        'M',
        'MD-06',
        'Consent forms from templates with signature capture; Medical, fitness, birth and death certificate data entry in hospital-configured formats',
        'Signed consents are immutable',
      ),
      I(
        'MR-03',
        'Patient merge and record corrections',
        'frontend',
        'P1',
        'M',
        'P-04',
        'Merge duplicate patients with a full audit and a reversal window; Correction requests with reason',
        'Merge is reversible within the window',
      ),
      I(
        'MR-04',
        'Medical records department tools',
        'frontend',
        'P2',
        'M',
        'MR-01',
        'Record completeness checks; Coding queue for diagnoses; Record request log',
        'Incomplete records are listed',
      ),
      I(
        'MR-05',
        'Records tests and end-to-end flow',
        'frontend',
        'P1',
        'S',
        'MR-03',
        'Unit tests; Playwright: upload, consent, merge',
        'E2E passes in CI',
      ),
      I(
        'BE-29',
        'Documents and records API',
        'backend',
        'P1',
        'L',
        'BE-09',
        'Object storage with signed URLs; Malware scan job; Merge transaction across tenant tables with audit; Retention rules',
        'Merge is atomic and audited',
      ),
    ],
  },
  {
    key: 'OPS',
    name: 'Hospital operations',
    weeks: 4,
    release: 'R4',
    goal: 'Rosters, blood bank, ambulance and housekeeping.',
    exit: 'Operational modules are available per hospital and can be enabled independently.',
    refs: 'Product Scope, Extensibility and Access Control',
    issues: [
      I(
        'OP-01',
        'Duty rosters and shifts',
        'frontend',
        'P1',
        'M',
        'D-03',
        'Shift templates; Rosters per department; Leave requests; On-call doctors shown in scheduling',
        'Roster conflicts are flagged',
      ),
      I(
        'OP-02',
        'Blood bank',
        'frontend',
        'P1',
        'L',
        'LB-04 IP-02',
        'Donor registry and collection; Component stock with expiry; Cross-match and issue; Transfusion reaction records; Full traceability',
        'Every unit is traceable from donor to recipient',
      ),
      I(
        'OP-03',
        'Ambulance management',
        'frontend',
        'P2',
        'M',
        'OP-01',
        'Vehicles and drivers; Trip requests and dispatch status; Charges to the bill',
        'Trips post charges to the encounter',
      ),
      I(
        'OP-04',
        'Housekeeping and bed cleaning tasks',
        'frontend',
        'P2',
        'S',
        'IP-01',
        'Cleaning tasks triggered by discharge and transfer; Completing a task makes the bed available',
        'Beds return to available only after cleaning',
      ),
      I(
        'OP-06',
        'Operations tests and end-to-end flow',
        'frontend',
        'P2',
        'S',
        'OP-02',
        'Unit tests; Playwright for blood issue and bed cleaning',
        'E2E passes in CI',
      ),
      I(
        'BE-30',
        'Operations API',
        'backend',
        'P1',
        'L',
        'BE-23 BE-19',
        'Roster, blood bank, ambulance and cleaning tables; Blood unit lifecycle state machine; Events',
        'RLS tests pass; Blood unit transitions validated',
      ),
      I(
        'OP-07',
        'Release R4 hardening and full-journey regression',
        'security',
        'P0',
        'M',
        'OP-06 MR-05 BE-30',
        'Full regression of every journey; Performance and load; Security and compliance review; Documentation refresh',
        'Checklist signed off',
      ),
    ],
  },
];

// Extra issues appended to existing core milestones, keyed by the core milestone key.
export const appended = {
  M1: [
    I(
      'F-15',
      'Shared building blocks: data grid, charts, forms, rich text',
      'frontend',
      'P1',
      'M',
      'F-08 F-09',
      'DataGrid wrapper on TanStack Table and TanStack Virtual with server pagination, sorting, filtering, column visibility, masked columns and row actions behind Can; Recharts chart wrappers using theme tokens, with lazy loading; Form kit on React Hook Form and Zod with i18n error messages; TipTap editor wrapper with sanitized output; Storybook-style example page for each',
      'New list, chart and form screens reuse these blocks; Heavy libraries load only on the routes that use them',
    ),
  ],
  M5: [
    I(
      'Q-01',
      'Walk-in registration and OPD token queue',
      'frontend',
      'P0',
      'M',
      'P-02 D-02',
      'Token issue per doctor and department; Live queue board through server-sent events; Call next, skip and recall; Priority flags',
      'Queue updates reach other screens within seconds',
    ),
    I(
      'Q-02',
      'Triage and vitals capture',
      'frontend',
      'P0',
      'M',
      'Q-01',
      'Nurse records vitals (blood pressure, pulse, temperature, oxygen saturation, weight, height), chief complaint and allergies; Abnormal values highlighted from configurable ranges; Shown to the doctor at consultation',
      'Vitals appear in the consultation view',
    ),
    I(
      'Q-03',
      'Waiting-room display screen',
      'frontend',
      'P2',
      'S',
      'Q-01',
      'Read-only route showing token numbers only, no patient data',
      'Display contains no PHI',
    ),
    I(
      'BE-18',
      'Queue and triage API',
      'backend',
      'P0',
      'M',
      'BE-11',
      'Per-doctor and per-day token sequences; vitals table; SSE stream per hospital; Events queue.token_issued, queue.called, vitals.recorded',
      'Token numbers are unique under concurrency',
    ),
  ],
  M6: [
    I(
      'C-07',
      'Imaging and procedure orders',
      'frontend',
      'P1',
      'M',
      'C-01 MD-01',
      'Order imaging and procedures from the service catalog; Priority and clinical notes; Orders emit order.placed',
      'Radiology and billing receive the orders by event',
    ),
    I(
      'C-08',
      'Referrals and follow-up scheduling',
      'frontend',
      'P1',
      'S',
      'C-01',
      'Refer to a department or doctor; Book follow-up from the consultation; Follow-up due list',
      'Follow-up creates a linked appointment',
    ),
    I(
      'C-09',
      'Printable prescription and visit summary',
      'frontend',
      'P0',
      'S',
      'C-02',
      'Print view with hospital letterhead from tenant config; Permission-gated and audited',
      'Print action is recorded in the audit log',
    ),
  ],
  M7: [
    I(
      'B-06',
      'Pending charges and bill assembly',
      'frontend',
      'P0',
      'M',
      'B-01 LB-03 PH-01',
      'Show charges posted from services, orders and dispenses; Add manual charges; Select charges to invoice; Prices from the active price list',
      'Invoices are built only from the charge ledger',
    ),
    I(
      'B-07',
      'Discounts, concessions and approvals',
      'frontend',
      'P1',
      'M',
      'B-06',
      'Discount reasons; Approval limits by permission; Audit',
      'Discounts above the limit need approval',
    ),
    I(
      'B-08',
      'Packages and bundled pricing',
      'frontend',
      'P2',
      'M',
      'B-06 MD-01',
      'Packages from master data applied to an encounter; Inclusions and exclusions',
      'Package charges replace individual charges',
    ),
    I(
      'B-09',
      'Cash register and day-end settlement',
      'frontend',
      'P1',
      'M',
      'B-03',
      'Shift open and close; Collections by payment mode; Reconciliation and handover',
      'Day-end totals reconcile with payments',
    ),
    I(
      'B-10',
      'Tax and invoice numbering',
      'frontend',
      'P1',
      'S',
      'B-02',
      'Tax per service category from tenant config; Invoice numbers per hospital and fiscal year; Printable invoice',
      'Numbers are gapless per fiscal year',
    ),
  ],
  M8: [
    I(
      'R-04',
      'Operational reports',
      'frontend',
      'P1',
      'M',
      'R-02 B-05 PH-07 LB-04',
      'OPD census, revenue and collections, doctor-wise activity, lab turnaround, pharmacy sales and stock',
      'Reports run through the asynchronous export path when large',
    ),
  ],
};

// Text patches to existing core issues. Each entry: [issueId, field, old, new]
export const patches = [
  ['C-01', 'title', 'Visit creation and notes', 'Encounter (OPD visit) creation and notes'],
  [
    'C-01',
    'tasks',
    'Start a visit from an appointment or walk-in',
    'Start an encounter from an appointment or the token queue, showing triage vitals and allergies',
  ],
  [
    'C-02',
    'tasks',
    'Add, edit and view prescriptions per visit',
    'Add, edit and view prescriptions per encounter using the drug master (generic and brand search); Allergy and duplicate-drug warnings; Prescription templates and favourites',
  ],
  ['C-03', 'title', 'Lab orders and results', 'Lab orders and result viewing'],
  [
    'C-03',
    'tasks',
    'Order tests and update status',
    'Order tests and panels from the lab test catalog; Track order status',
  ],
  [
    'C-03',
    'tasks',
    'Enter and view results',
    'View results once verified (entry happens in the laboratory module)',
  ],
  [
    'BE-12',
    'tasks',
    'visits, prescriptions and lab_orders',
    'encounters (opd, ipd, er), clinical notes, a unified orders table for lab, imaging, procedure, medication and diet with order.placed events, prescriptions',
  ],
  [
    'BE-13',
    'tasks',
    'invoices, items and payments',
    'charges ledger fed by order, dispense and service events, invoices assembled from charges, payments, cash register sessions and fiscal-year invoice numbering',
  ],
  ['BE-13', 'deps', 'BE-12', 'BE-12 BE-19 BE-21'],
  [
    'BE-14',
    'tasks',
    'Read-replica queries',
    'Read-replica queries for operational reports (OPD census, revenue, lab turnaround, stock)',
  ],
  [
    'H-04',
    'tasks',
    'Patient to appointment to visit to invoice to payment',
    'Registration, token, triage, consultation, lab order, result, prescription, pharmacy dispense, invoice and payment',
  ],
];

export const nameOverrides = {
  M5: 'Appointments, queue and triage',
  M6: 'Clinical (OPD consultation and orders)',
  M7: 'Billing and charge ledger',
  M11: 'Hardening and pilot launch (R1)',
};
export const weeksOverrides = { M5: 5, M6: 4, M7: 4 };
export const order = [
  'M0',
  'M1',
  'M2',
  'M3',
  'M4',
  'MD',
  'M5',
  'M6',
  'LAB',
  'RAD',
  'PHX',
  'M7',
  'M8',
  'M9',
  'M10',
  'M11',
  'IPD',
  'NUR',
  'DIS',
  'ER',
  'OT',
  'INS',
  'MRD',
  'OPS',
  'BL',
];
export const coreRelease = {
  M0: 'R1',
  M1: 'R1',
  M2: 'R1',
  M3: 'R1',
  M4: 'R1',
  M5: 'R1',
  M6: 'R1',
  M7: 'R1',
  M8: 'R1',
  M9: 'R1',
  M10: 'R1',
  M11: 'R1',
  BL: '',
};
