// Single source of truth for the project roadmap. Seeded into GitHub by seed.mjs.
// Task and acceptance lists are semicolon-separated strings (keep semicolons out of the text).

const L = (s) =>
  s
    ? s
        .split(';')
        .map((x) => x.trim())
        .filter(Boolean)
    : [];
const I = (id, title, area, pri, size, deps, tasks, ac, extra = {}) => ({
  id,
  title,
  area,
  pri,
  size,
  deps: deps ? deps.split(' ') : [],
  tasks: L(tasks),
  ac: L(ac),
  ...extra,
});

export const labels = [
  ...['feature:1D76DB', 'chore:C5DEF5', 'bug:D73A4A', 'docs:0075CA', 'spike:D4C5F9'].map((x) => ({
    name: `type:${x.split(':')[0]}`,
    color: x.split(':')[1],
    description: 'Issue type',
  })),
  ...[
    'frontend:0E8A16',
    'backend:5319E7',
    'infra:FBCA04',
    'security:B60205',
    'docs:0075CA',
    'product:BFD4F2',
  ].map((x) => ({
    name: `area:${x.split(':')[0]}`,
    color: x.split(':')[1],
    description: 'Area of the system',
  })),
  ...['R1', 'R2', 'R3', 'R4'].map((r, i) => ({
    name: `release:${r}`,
    color: ['0E8A16', '1D76DB', '5319E7', 'B60205'][i],
    description: `Release ${r}`,
  })),
  { name: 'P0', color: 'B60205', description: 'Must have for the milestone' },
  { name: 'P1', color: 'D93F0B', description: 'Should have' },
  { name: 'P2', color: 'FBCA04', description: 'Nice to have' },
  { name: 'size:S', color: 'C2E0C6', description: 'About half a day or less with Claude Code' },
  { name: 'size:M', color: 'BFDADC', description: '1 to 2 days' },
  { name: 'size:L', color: 'F9D0C4', description: '3 to 5 days. Consider splitting' },
  { name: 'status:in-progress', color: 'FEF2C0', description: 'Being worked on' },
  { name: 'status:in-review', color: 'C5DEF5', description: 'PR open' },
  {
    name: 'status:blocked',
    color: 'B60205',
    description: 'Blocked. State the blocker in a comment',
  },
  {
    name: 'status:needs-decision',
    color: 'D4C5F9',
    description: 'Waiting on a product or technical decision',
  },
];

export const dod = (area) =>
  area === 'backend'
    ? [
        'Migrations are additive, every tenant table has tenant_id + RLS, and cross-tenant tests pass',
        'OpenAPI spec updated and no breaking change without a version bump',
        'Permissions registered, audit events and domain events emitted where CLAUDE.md requires',
        'Mutations that create or charge accept an Idempotency-Key',
        'Lint, typecheck, and tests pass in CI',
        'PR body contains Closes #<this issue>',
      ]
    : [
        'Follows CLAUDE.md conventions (feature module, tenant-scoped query keys, usePermission or Can, i18n keys, server-side pagination)',
        'Tests cover happy path, validation, permission absent, flag off, and two tenants where relevant',
        'pnpm lint, pnpm typecheck, and pnpm test pass',
        '/tenant-safety-check and /phi-check run on the diff where data or access is touched',
        'Docs or CLAUDE.md updated if a contract or convention changed',
        'PR body contains Closes #<this issue>',
      ];

const core = [
  {
    key: 'M0',
    title: 'M0 Setup',
    weeks: 1,
    goal: 'Repository, tooling, CI and local services.',
    exit: 'A clean clone installs and runs dev, test and build. CI is green. Hooks are active.',
    refs: 'Package Manager, Commands, Technology Decisions',
    issues: [
      I(
        'S-01',
        'Create monorepo, branch protection and conventions',
        'infra',
        'P0',
        'S',
        '',
        'Create private GitHub repo as a pnpm workspace (pnpm-workspace.yaml listing apps/* and packages/*); Add README, .gitignore, .gitattributes (* text=auto eol=lf), .editorconfig; Protect main (PR required, CI required, no force push); Enable Dependabot alerts',
        'Direct pushes to main are blocked; Repo clones and installs on a clean Windows machine',
      ),
      I(
        'S-02',
        'Scaffold apps/web (Vite + React + TypeScript) with pnpm',
        'frontend',
        'P0',
        'S',
        'S-01',
        'Create apps/web with pnpm create vite (react-ts) and add packages/contract; Root scripts run across workspaces and pnpm --filter web works; Strict tsconfig and @/ alias to apps/web/src; Set packageManager, .nvmrc and engines; Remove template demo code',
        'pnpm dev and pnpm build run; pnpm install --frozen-lockfile works',
      ),
      I(
        'S-03',
        'Linting, formatting, tests and git hooks',
        'frontend',
        'P0',
        'M',
        'S-02',
        'ESLint (typescript-eslint, react-hooks, jsx-a11y) and Prettier; Vitest + React Testing Library; Scripts from CLAUDE.md Commands (analyze, e2e, gen:api can be stubs); lint-staged + simple-git-hooks pre-commit',
        'pnpm lint, typecheck, test pass on a clean tree; Pre-commit formats staged files',
      ),
      I(
        'S-04',
        'Tailwind CSS and shadcn/ui with tenant-ready theme tokens',
        'frontend',
        'P0',
        'S',
        'S-02',
        'Install Tailwind and init shadcn/ui; Define colors and radius as CSS variables on :root; Document how to add components',
        'Changing CSS variables re-themes components at runtime',
      ),
      I(
        'S-05',
        'Test infrastructure: MSW, Playwright, render helpers',
        'frontend',
        'P1',
        'M',
        'S-03',
        'Wire MSW for browser and node; Playwright config with one smoke test; renderWithProviders helper (query client, router, i18n, session, tenant, policy); Synthetic data factories',
        'A sample test uses MSW; Playwright smoke test passes locally',
      ),
      I(
        'S-06',
        'CI pipeline with GitHub Actions',
        'infra',
        'P0',
        'M',
        'S-03',
        'Workflow: pnpm setup with cache, frozen install, lint, typecheck, test, build; pnpm audit report and Dependabot config; Require checks on PRs',
        'PRs show required checks; A failing lint blocks merge',
      ),
      I(
        'S-07',
        'Local services with Docker Compose',
        'infra',
        'P1',
        'S',
        '',
        'Postgres and Mailpit by default, with MinIO and Redis behind a full profile, and healthchecks; Named volumes for data; .env.example and README section Run locally on Windows',
        'docker compose up -d brings all services healthy; Data survives a restart',
      ),
      I(
        'S-08',
        'Adopt Claude Code project config and GitHub templates',
        'docs',
        'P1',
        'S',
        'S-01',
        'Commit CLAUDE.md and .claude/ (settings, hooks, skills, agents); Add issue and PR templates; Verify /hooks and /permissions',
        'Hooks block npm and .env reads; Templates appear when creating issues and PRs',
      ),
    ],
  },
  {
    key: 'M1',
    title: 'M1 Foundation',
    weeks: 3,
    goal: 'Multi-tenant app shell, access layer and plug-in architecture, running on a mock backend. Backend skeleton and tenancy in parallel.',
    exit: 'Two sample hospitals in the mock app: switching works with isolated cache, nav is permission and flag gated, and an example feature plugs in without core edits.',
    refs: 'Multi-Tenancy, Extensibility and Access Control, Technology Decisions',
    issues: [
      I(
        'F-01',
        'App shell, providers and folder structure',
        'frontend',
        'P0',
        'M',
        'S-03 S-04',
        'Create src/ structure per CLAUDE.md; Providers: React Query client, Redux Toolkit store for client and workflow state (with a reset action for tenant switch and logout), Router, i18n and placeholder session, tenant and policy contexts; Global error boundary',
        'App renders the shell; Structure matches CLAUDE.md',
      ),
      I(
        'F-02',
        'API client, interceptors and error handling',
        'frontend',
        'P0',
        'M',
        'F-01',
        'Thin fetch wrapper with middleware (tenant consistency header); 401 to session handling, 403 to policy refresh, 429 with Retry-After backoff; Retry with jitter for idempotent requests only; AbortController support; Standard error shape with friendly messages; pnpm gen:api pipeline (openapi-typescript and openapi-fetch)',
        'Unit tests cover retry, 401, 403 and 429; No raw server errors reach the UI',
      ),
      I(
        'F-03',
        'Session bootstrap (GET /session)',
        'frontend',
        'P0',
        'M',
        'F-01 F-02',
        'Session types (user, memberships, active tenant, tenant config, policy); SessionProvider with loading, error and unauthenticated states; Session query via React Query exposed through context; Redirect to login when unauthenticated',
        'Rendering is blocked until the session resolves; Unauthenticated users reach login',
      ),
      I(
        'F-04',
        'MSW mock backend v1',
        'frontend',
        'P0',
        'S',
        'F-03',
        'Handlers for session, switch-tenant and policy; Two sample hospitals with different config and features; Users with one and two memberships; Roles with different permissions',
        'Dev app works end to end with no backend',
      ),
      I(
        'F-05',
        'Active tenant, hospital picker and switcher',
        'frontend',
        'P0',
        'M',
        'F-03',
        'Picker for multi-hospital users and header switcher; Switch flow: POST /session/switch-tenant, clear Query cache, reset any global stores, abort requests, reload policy and config; Tenant-scoped query key factory; Handle cross-tab mismatch response',
        'A test proves no data from the previous tenant remains after switching',
      ),
      I(
        'F-06',
        'Tenant config and runtime theming',
        'frontend',
        'P1',
        'M',
        'F-05',
        'Apply theme variables and logo from tenant config; Tenant-aware formatters for date, time, currency, number; Timezone helpers',
        'Two sample hospitals look and format differently; No hardcoded hospital strings',
      ),
      I(
        'F-07',
        'Access layer: AccessPolicy, usePermission, Can, PermissionGuard',
        'frontend',
        'P0',
        'M',
        'F-03',
        'Policy context backed by the session query; usePermission with scope support; Can component and PermissionGuard for routes; Refresh policy on interval and on 403; Test that fails on role-name comparisons',
        'Removing a permission in MSW hides the UI after refresh without a reload',
      ),
      I(
        'F-08',
        'Feature registry, route and nav generation, extension slots',
        'frontend',
        'P0',
        'L',
        'F-07',
        'FeatureManifest and SlotId types; Registry filtering by flag and permission; Lazy route generation and nav generation; Slot component plus dashboard widget and settings section slots',
        'Adding a manifest adds route, nav and slot content with no core edits',
      ),
      I(
        'F-09',
        'i18n foundation',
        'frontend',
        'P1',
        'S',
        'F-01',
        'i18next and react-i18next with namespaces per feature loaded on demand; Language from tenant config with fallback; Test for missing keys',
        'Switching tenant locale changes the UI language',
      ),
      I(
        'F-10',
        'Layout, navigation and system pages',
        'frontend',
        'P1',
        'M',
        'F-08',
        'Responsive shell with header switcher and user menu; Sidebar generated from the registry; 403, 404, error and suspended-hospital pages; Skeleton and loading patterns',
        'Keyboard navigable; Passes axe checks',
      ),
      I(
        'F-11',
        'Performance guardrails',
        'frontend',
        'P1',
        'S',
        'F-08 S-06',
        'Bundle budget script (initial 300 KB gz, route chunk 150 KB gz, heavy lazy chunks 250 KB gz, CSS 60 KB gz) failing CI and reporting size change per PR; Dependency review checklist in the PR template (reason, size, licence, maintenance); web-vitals reporting stub tagged by route with no PHI; pnpm analyze report',
        'CI fails when a budget is exceeded',
      ),
      I(
        'F-12',
        'Error reporting with PHI scrubbing',
        'security',
        'P1',
        'S',
        'F-01',
        'Add Sentry (free tier, errors only) loaded lazily after first paint, with beforeSend scrubbing; Logging wrapper that forbids PHI fields; Document the policy',
        'A test proves request bodies, response bodies and patient fields are stripped',
      ),
      I(
        'F-13',
        'Sample feature proving the plug-in architecture',
        'frontend',
        'P1',
        'S',
        'F-08',
        'Example feature with manifest, route, nav, permission, flag, slot contribution and settings section; MSW handler and tests; Keep as a template',
        'Flag off hides everything; Permission absent hides actions; No core file changed',
      ),
      I(
        'F-14',
        'Foundation test suite',
        'frontend',
        'P0',
        'M',
        'F-08',
        'Tests for cache isolation on switch, permission gating, flag gating, registry filtering, policy refresh and API client behavior',
        'All listed behaviors covered and running in CI',
      ),
      I(
        'BE-01',
        'Backend skeleton (apps/api: Fastify, TypeBox, Drizzle)',
        'backend',
        'P0',
        'M',
        'S-07',
        'Create apps/api with Fastify and tsx watch; Core folder layout and feature plugin template per CLAUDE.md Backend; Config with validation; Health endpoint; Drizzle and drizzle-kit wired to local Postgres; pino with PHI redaction; Dockerfile (multi-stage, slim); Vitest against local Postgres; CI job',
        'Container runs locally; CI is green',
      ),
      I(
        'BE-02',
        'Tenancy foundation: tenants and row-level security',
        'backend',
        'P0',
        'L',
        'BE-01',
        'SQL migrations via drizzle-kit; tenants and tenant_features tables; tenant_id convention and RLS policy template; Tenant hook opening a transaction per request with SET LOCAL app.tenant_id; Cross-tenant read and write tests',
        'Automated tests show tenant A cannot read or write tenant B rows via API or SQL under the app role',
      ),
      I(
        'BE-03',
        'OpenAPI contract and client generation',
        'backend',
        'P0',
        'S',
        'BE-01',
        'Generate OpenAPI from TypeBox route schemas via @fastify/swagger into packages/contract; Wire pnpm gen:api to generate web client types; CI check for breaking changes; Error and cursor pagination envelope schemas',
        'Frontend generates a typed client from the spec',
      ),
    ],
  },
  {
    key: 'M2',
    title: 'M2 Auth and access',
    weeks: 3,
    goal: 'Staff authentication, onboarding by invite, and policy-driven access against the real backend.',
    exit: 'Staff can log in with MFA, invited users onboard, and permissions from the backend drive the UI.',
    refs: 'Extensibility and Access Control, Security and Privacy, Multi-Tenancy',
    issues: [
      I(
        'A-01',
        'Login page and sign-in flow',
        'frontend',
        'P0',
        'M',
        'F-03 F-04',
        'Generic login page (email and password); Error and lockout messaging; Redirect to the intended route; Hospital picker after login for multiple memberships',
        'Login works against MSW and the real API; No user enumeration in messages',
      ),
      I(
        'A-02',
        'MFA enrollment and challenge',
        'frontend',
        'P1',
        'M',
        'A-01',
        'TOTP enrollment with QR code and recovery codes; Challenge step at login; Enforcement driven by policy or tenant setting',
        'MFA required roles cannot reach the app without completing it',
      ),
      I(
        'A-03',
        'Invite acceptance and password reset',
        'frontend',
        'P0',
        'M',
        'A-01',
        'Accept-invite page (set password, MFA); Forgot and reset password; Expired and used link handling',
        'Flows work end to end with Mailpit locally',
      ),
      I(
        'A-04',
        'Session lifecycle: inactivity logout and multi-tab sync',
        'frontend',
        'P0',
        'S',
        'A-01',
        'Tenant-configurable idle timeout with warning; Logout clears caches and state; BroadcastChannel sync across tabs; Session-expired handling',
        'Idle logout and cross-tab logout covered by tests',
      ),
      I(
        'A-05',
        'Route protection and deep links',
        'frontend',
        'P0',
        'S',
        'A-01 F-07',
        'Guards on all routes; Deep link handling (server resolves tenant and checks membership); Forbidden page that does not leak existence',
        'Opening a link to another hospital without membership shows 403 and no data',
      ),
      I(
        'A-06',
        'Profile and account settings',
        'frontend',
        'P2',
        'S',
        'A-01',
        'View profile and change password; Manage MFA; List and revoke active sessions',
        'User can revoke another session and it logs out',
      ),
      I(
        'BE-04',
        'Authentication and sessions API',
        'backend',
        'P0',
        'L',
        'BE-02',
        'users, user_identities (provider and subject) and memberships tables; Argon2id passwords; httpOnly secure cookie sessions with refresh rotation; /session and /session/switch-tenant; Lockout and rate limits; Invite and reset flows; TOTP MFA',
        'Auth flows covered by tests; Sessions bind to one active tenant',
      ),
      I(
        'BE-05',
        'Roles, permissions and AccessPolicy API',
        'backend',
        'P0',
        'L',
        'BE-04',
        'roles and role_permissions tables (tenant-scoped, built-ins seeded); Permission registry fed by feature modules; GET /me/policy with version; Permission guard decorator and scope filters',
        'Changing a role bumps the policy version; Guards enforce permissions in tests',
      ),
      I(
        'BE-06',
        'Audit log and transactional outbox',
        'backend',
        'P0',
        'M',
        'BE-02',
        'Append-only audit_log partitioned by month; Interceptor logging PHI reads and writes; Outbox table and dispatcher to the job queue (pg-boss in phase 1); Event contract from CLAUDE.md',
        'A rolled-back transaction emits no event; Audit rows are immutable',
      ),
      I(
        'BE-07',
        'Per-tenant rate limiting and idempotency',
        'backend',
        'P1',
        'M',
        'BE-04',
        'Rate limits per tenant and per user (in-process in phase 1, Redis in phase 2); Idempotency-Key middleware that stores results; 429 with Retry-After',
        'Replaying a request with the same key returns the first result',
      ),
      I(
        'BE-08',
        'Notifier abstraction for staff email',
        'backend',
        'P2',
        'S',
        'BE-01',
        'Notifier interface; Email adapter (SMTP or SES) with Mailpit locally; Templates for invite and password reset',
        'Invite and reset emails arrive in Mailpit',
      ),
    ],
  },
  {
    key: 'M3',
    title: 'M3 Patients',
    weeks: 2,
    goal: 'Register, find, view and edit patients. First staging deployment.',
    exit: 'A receptionist can register and find patients, a doctor can view them, and staging is deployed.',
    refs: 'Domain Types, Scalability, Security and Privacy',
    issues: [
      I(
        'P-01',
        'Patient list with server-side search and pagination',
        'frontend',
        'P0',
        'M',
        'F-08',
        'Use the add-list-view skill; Search by name, phone, MRN; Cursor pagination with page sizes of 25 to 100; TanStack Table for the grid (sorting, column visibility) and TanStack Virtual for long result pages; Masked phone and MRN where appropriate',
        'Handles 10k+ rows smoothly; No client-side filtering of full data',
      ),
      I(
        'P-02',
        'Patient registration form',
        'frontend',
        'P0',
        'M',
        'P-01',
        'React Hook Form + Zod; Fields incl. phone, email, address and contactConsent (given, at, recordedBy); Duplicate warning before save; Show MRN after creation',
        'Requires patient:create; Validation and errors covered by tests',
      ),
      I(
        'P-03',
        'Patient detail view with extension slots',
        'frontend',
        'P0',
        'M',
        'P-01',
        'Header summary and demographics tab; Render patient.detail.tabs and patient.detail.actions slots; Viewing triggers the audit log via the API',
        'A test feature can add a tab without editing this module',
      ),
      I(
        'P-04',
        'Edit patient and field-level permissions',
        'frontend',
        'P1',
        'M',
        'P-03',
        'Edit form with optimistic update and rollback; Field masking per permission (patient.<field>:read); Conflict handling on concurrent edits',
        'Roles without a field permission never see the value in UI or network responses',
      ),
      I(
        'P-05',
        'Duplicate detection and search UX',
        'frontend',
        'P2',
        'S',
        'P-02',
        'Fuzzy suggestions during registration; Clear no-results state; No merge in v1',
        'Likely duplicates surface before saving',
      ),
      I(
        'P-06',
        'Patients tests and end-to-end flow',
        'frontend',
        'P0',
        'S',
        'P-04',
        'Unit tests for forms and permissions; Playwright: register, search, open, edit; Two-tenant isolation e2e',
        'E2E passes in CI',
      ),
      I(
        'BE-09',
        'Patients API',
        'backend',
        'P0',
        'L',
        'BE-05 BE-06',
        'patients table with per-tenant MRN sequence and contact_consent; Indexes on tenant_id and pg_trgm; CRUD with cursor pagination and search; Field-level permission filtering; Audit and events patient.registered and patient.updated',
        'RLS tests pass; Search stays fast on a large seeded dataset',
      ),
      I(
        'INF-01',
        'Staging environment and deploy pipeline',
        'infra',
        'P1',
        'L',
        'S-06 BE-01',
        'IaC (Terraform or OpenTofu) for CDN-hosted SPA, container service, managed Postgres and object storage (add Redis when scaling out); GitHub Actions deploy on merge to main using OIDC, no long-lived keys; Secrets manager; Synthetic seed data only',
        'Merge to main deploys staging automatically; No real patient data in staging',
      ),
    ],
  },
  {
    key: 'M4',
    title: 'M4 Doctors, departments, staff',
    weeks: 2,
    goal: 'Departments, doctors and staff user management.',
    exit: 'A hospital admin can manage departments, doctors and staff accounts.',
    refs: 'Domain Types, Extensibility and Access Control',
    issues: [
      I(
        'D-01',
        'Departments management',
        'frontend',
        'P1',
        'S',
        'F-08',
        'List, create, edit and archive departments; Permission-gated actions',
        'Covered by tests',
      ),
      I(
        'D-02',
        'Doctors management',
        'frontend',
        'P1',
        'M',
        'D-01',
        'Doctor profile linked to a user, department and specialization; Working hours and availability config used by scheduling',
        'Availability saved and reflected by the API',
      ),
      I(
        'D-03',
        'Staff user management for hospital admins',
        'frontend',
        'P0',
        'M',
        'A-03',
        'List users; Invite by email with a role; Deactivate and reactivate; Revoke sessions; Bulk CSV invite',
        'Deactivated users lose access immediately',
      ),
      I(
        'D-04',
        'Tests and end-to-end for this milestone',
        'frontend',
        'P1',
        'S',
        'D-03',
        'Unit tests; Playwright for invite, accept and deactivate',
        'E2E passes in CI',
      ),
      I(
        'BE-10',
        'Departments, doctors and staff users API',
        'backend',
        'P0',
        'L',
        'BE-05 BE-08',
        'Tables and availability schedule model; Invite flow reuse; Deactivation revokes sessions; Audit and events',
        'RLS tests pass; Deactivation verified by tests',
      ),
    ],
  },
  {
    key: 'M5',
    title: 'M5 Appointments',
    weeks: 3,
    goal: 'Booking, calendar and lifecycle of appointments without double booking.',
    exit: 'Appointments can be booked and changed without overlaps, walk-ins get tokens in a live queue, and nurses record triage vitals before consultation.',
    refs: 'Domain Types, Scalability',
    issues: [
      I(
        'AP-01',
        'Appointment list with filters',
        'frontend',
        'P0',
        'M',
        'P-01 D-02',
        'Filters by date range, doctor and status; Server pagination; Row actions behind Can',
        'Matches the add-list-view pattern',
      ),
      I(
        'AP-02',
        'Create appointment with conflict handling',
        'frontend',
        'P0',
        'L',
        'AP-01',
        'Patient search and doctor selection; Slot picker from availability; Handle 409 conflicts with alternative slots; Idempotency key; appointment.form.fields slot',
        'Two simultaneous bookings cannot both succeed',
      ),
      I(
        'AP-03',
        'Calendar views (day and week per doctor)',
        'frontend',
        'P1',
        'L',
        'AP-01',
        'Calendar built on FullCalendar (free plugins) or react-big-calendar, lazy-loaded in its own chunk; Tenant timezone throughout; Render only the visible range',
        'Smooth with a busy week; Chunk within budget',
      ),
      I(
        'AP-04',
        'Reschedule, cancel, complete and no-show',
        'frontend',
        'P0',
        'M',
        'AP-02',
        'Actions with reason capture; Optimistic updates with rollback; appointment.row.badges slot',
        'Status transitions validated by tests',
      ),
      I(
        'AP-05',
        'Appointment tests and end-to-end',
        'frontend',
        'P0',
        'S',
        'AP-04',
        'Unit tests; Playwright: book, reschedule, cancel; Two-tenant isolation',
        'E2E passes in CI',
      ),
      I(
        'BE-11',
        'Appointments API',
        'backend',
        'P0',
        'L',
        'BE-09 BE-10',
        'appointments table; Exclusion constraint on tenant_id, doctor_id and tstzrange; Availability queries; Events for created, rescheduled, cancelled, completed and no_show; UTC storage',
        'Concurrency test proves no double booking',
      ),
    ],
  },
  {
    key: 'M6',
    title: 'M6 Clinical',
    weeks: 3,
    goal: 'Visits, prescriptions, lab orders and the clinical timeline.',
    exit: 'Doctors can run an OPD consultation with triage data, place lab, imaging and medication orders through the unified order model, and view a patient timeline.',
    refs: 'Domain Types, Security and Privacy',
    issues: [
      I(
        'C-01',
        'Visit creation and notes',
        'frontend',
        'P0',
        'M',
        'AP-04',
        'Start a visit from an appointment or walk-in; Notes and diagnosis behind field-level permission; Drafts stored server-side, never in browser storage',
        'No PHI in browser storage (tested)',
      ),
      I(
        'C-02',
        'Prescriptions',
        'frontend',
        'P0',
        'M',
        'C-01',
        'Add, edit and view prescriptions per visit; Validation of dosage fields',
        'Permission-gated and covered by tests',
      ),
      I(
        'C-03',
        'Lab orders and results',
        'frontend',
        'P0',
        'M',
        'C-01',
        'Order tests and update status; Enter and view results',
        'Nurse and doctor permissions differ as designed',
      ),
      I(
        'C-04',
        'Patient clinical timeline tab',
        'frontend',
        'P1',
        'M',
        'C-02 C-03',
        'Contributed via patient.detail.tabs; Virtualized with load more, and filterable by type',
        'Works without editing the patients module',
      ),
      I(
        'C-05',
        'Clinical permissions and limited nurse view',
        'frontend',
        'P1',
        'S',
        'C-01',
        'Verify per-role views; Mask diagnosis where required',
        'Permission matrix tests pass',
      ),
      I(
        'C-06',
        'Clinical tests and end-to-end',
        'frontend',
        'P0',
        'S',
        'C-04',
        'Playwright: visit, prescription, lab order; Permission-absent cases',
        'E2E passes in CI',
      ),
      I(
        'BE-12',
        'Clinical API',
        'backend',
        'P0',
        'L',
        'BE-11',
        'visits, prescriptions and lab_orders; Field-level diagnosis permissions; Amendments with history instead of overwrites; Events and audit',
        'Edits create history; RLS tests pass',
      ),
    ],
  },
  {
    key: 'M7',
    title: 'M7 Billing',
    weeks: 3,
    goal: 'Invoices, payments and corrections with strong integrity.',
    exit: 'Charges from services, orders and dispenses post to a ledger, invoices are assembled from charges, paid, and immutable with credit notes for corrections.',
    refs: 'Domain Types, Scalability (idempotency)',
    issues: [
      I(
        'B-01',
        'Create invoice from a visit or appointment',
        'frontend',
        'P0',
        'M',
        'C-01',
        'Line items and totals using tenant currency; Draft then issue flow',
        'Amounts handled safely (minor units)',
      ),
      I(
        'B-02',
        'Invoice list, detail and print view',
        'frontend',
        'P0',
        'M',
        'B-01',
        'Server-paginated list and detail; Print or PDF gated by permission and audited',
        'Print action recorded in the audit log',
      ),
      I(
        'B-03',
        'Record payments',
        'frontend',
        'P0',
        'M',
        'B-02',
        'Partial and full payments with payment modes; Idempotency key and double-click protection',
        'Double submit creates one payment',
      ),
      I(
        'B-04',
        'Void and credit notes',
        'frontend',
        'P1',
        'M',
        'B-02',
        'Issued invoices cannot be edited; Credit note flow with reason',
        'Immutability enforced in UI and API',
      ),
      I(
        'B-05',
        'Billing tests and end-to-end',
        'frontend',
        'P0',
        'S',
        'B-04',
        'Playwright: invoice, pay, credit note; Role matrix checks',
        'E2E passes in CI',
      ),
      I(
        'BE-13',
        'Billing API',
        'backend',
        'P0',
        'L',
        'BE-12',
        'invoices, items and payments; Immutable issued invoices and credit notes; Idempotency on creates and payments; Per-tenant currency; Events invoice.issued and invoice.paid',
        'Replay and concurrency tests pass',
      ),
    ],
  },
  {
    key: 'M8',
    title: 'M8 Dashboards and reports',
    weeks: 2,
    goal: 'Role-based dashboards and asynchronous reports.',
    exit: 'Each role sees a useful dashboard, and large reports run as background jobs.',
    refs: 'Extensibility and Access Control, Scalability',
    issues: [
      I(
        'R-01',
        'Role-based dashboards via widget slots',
        'frontend',
        'P1',
        'M',
        'F-08 AP-05',
        'Widgets contributed through dashboard.widgets; Widgets filtered by permission and flag; Failure of one widget does not break the page',
        'Disabling a feature removes its widget',
      ),
      I(
        'R-02',
        'Reports with asynchronous export',
        'frontend',
        'P1',
        'L',
        'R-01',
        'Request, poll with backoff, then download via signed URL; Permission gated and audited',
        'Large export does not block the UI',
      ),
      I(
        'R-03',
        'Dashboards and reports tests and performance checks',
        'frontend',
        'P1',
        'S',
        'R-02',
        'Unit tests; Lighthouse and bundle checks for the route',
        'Within bundle budget',
      ),
      I(
        'BE-14',
        'Reporting API and workers',
        'backend',
        'P1',
        'L',
        'BE-13',
        'Read-replica queries; Workers on the job queue (pg-boss, BullMQ once Redis is added); Per-tenant quotas; Signed URLs and retention policy',
        'Heavy report does not slow other tenants',
      ),
    ],
  },
  {
    key: 'M9',
    title: 'M9 Platform admin',
    weeks: 2,
    goal: 'Onboard and manage hospitals without touching the database.',
    exit: 'A platform admin can create, configure, suspend and offboard a hospital end to end, without access to patient data.',
    refs: 'Extensibility and Access Control (Hospital onboarding)',
    issues: [
      I(
        'PL-01',
        'Platform admin shell and guard',
        'frontend',
        'P0',
        'S',
        'F-10',
        'platform_admin only; Separate navigation; No patient-data routes',
        'Other roles get 403',
      ),
      I(
        'PL-02',
        'Create hospital wizard',
        'frontend',
        'P0',
        'M',
        'PL-01',
        'Name, slug, locale, timezone, currency, branding, region; Validation and preview',
        'New hospital appears in the list',
      ),
      I(
        'PL-03',
        'Feature toggles and limits per hospital',
        'frontend',
        'P0',
        'M',
        'PL-02',
        'Toggle feature flags; Set limits such as users and storage',
        'Toggling takes effect on the next policy refresh',
      ),
      I(
        'PL-04',
        'Invite the first hospital admin',
        'frontend',
        'P0',
        'S',
        'PL-02',
        'Invite by email; Resend and revoke',
        'Invitee can onboard via A-03',
      ),
      I(
        'PL-05',
        'Suspend, reactivate and offboard a hospital',
        'frontend',
        'P1',
        'M',
        'PL-02',
        'Suspend blocks logins and keeps data; Offboard: export then scheduled deletion; Confirmation dialogs',
        'Suspended users see the suspended page',
      ),
      I(
        'PL-06',
        'Platform audit view',
        'frontend',
        'P2',
        'S',
        'PL-01',
        'List platform actions with filters',
        'Actions are searchable by hospital and actor',
      ),
      I(
        'PL-07',
        'Platform tests and end-to-end',
        'frontend',
        'P0',
        'S',
        'PL-05',
        'Playwright: onboard a hospital; Verify platform admin cannot reach patient data',
        'E2E passes in CI',
      ),
      I(
        'BE-15',
        'Platform admin API',
        'backend',
        'P0',
        'L',
        'BE-05 BE-08',
        'Tenant CRUD with seeded built-in roles; Feature flags and settings; First admin invite; Suspend and offboarding jobs; Bootstrap script for the first platform_admin with MFA; Audit; Break-glass access design',
        'Platform admin cannot read patient rows (tested)',
      ),
    ],
  },
  {
    key: 'M10',
    title: 'M10 Roles management',
    weeks: 2,
    goal: 'Hospital admins customize roles and permissions.',
    exit: 'A hospital admin can create roles, edit permissions and see the effects live.',
    refs: 'Extensibility and Access Control (Roles)',
    issues: [
      I(
        'RP-01',
        'Role list and custom role editor',
        'frontend',
        'P0',
        'M',
        'F-08 BE-05',
        'List roles; Create, rename and delete custom roles; Built-in roles protected',
        'Custom role appears in the invite flow',
      ),
      I(
        'RP-02',
        'Permission matrix editor',
        'frontend',
        'P0',
        'M',
        'RP-01',
        'Permissions grouped by feature with scope selection; Safeguard: cannot remove the last admin capability',
        'Changes bump the policy version',
      ),
      I(
        'RP-03',
        'View-as-role preview',
        'frontend',
        'P1',
        'M',
        'RP-02',
        'Preview nav and actions for a role before saving',
        'Preview matches real behavior',
      ),
      I(
        'RP-04',
        'Policy change propagation tests',
        'frontend',
        'P0',
        'S',
        'RP-02',
        'Test that edits reach active sessions after refresh; Test lockout safeguards',
        'Tests run in CI',
      ),
      I(
        'BE-16',
        'Roles management API',
        'backend',
        'P0',
        'M',
        'BE-05',
        'Custom role CRUD; Built-in role protection; Policy version bump; Audit; Last-admin safeguard',
        'Cannot remove the last admin (tested)',
      ),
    ],
  },
  {
    key: 'M11',
    title: 'M11 Hardening and launch',
    weeks: 4,
    goal: 'Performance, accessibility, security, resilience and a pilot launch.',
    exit: 'Budgets met, security and accessibility reviewed, disaster recovery proven, and a pilot hospital live.',
    refs: 'Scalability, Security and Privacy, Technology Decisions',
    issues: [
      I(
        'H-01',
        'Performance audit and bundle tuning',
        'frontend',
        'P0',
        'M',
        'R-03',
        'Lighthouse CI and web-vitals review; Verify 10k-row datasets stay fast through pagination; Run a 30-minute memory soak; Check every Performance Strategy budget; Fix budget violations',
        'LCP, INP and CLS within targets on staging',
      ),
      I(
        'H-02',
        'Accessibility audit (WCAG 2.1 AA)',
        'frontend',
        'P0',
        'M',
        'R-03',
        'axe in CI; Keyboard and screen reader pass on critical flows',
        'No critical axe violations',
      ),
      I(
        'H-03',
        'Threat model and security review',
        'security',
        'P0',
        'M',
        'BE-16',
        'Threat model per module; Review tenant isolation tests; CSP and security headers; Dependency audit; Plan an external penetration test',
        'Findings triaged into issues',
      ),
      I(
        'H-04',
        'End-to-end suite for critical flows',
        'frontend',
        'P0',
        'M',
        'PL-07',
        'Patient to appointment to visit to invoice to payment; Two-tenant and role-matrix checks',
        'Runs in CI on every PR',
      ),
      I(
        'H-05',
        'Load testing with k6',
        'backend',
        'P0',
        'M',
        'BE-14',
        'Mixed-tenant scenarios and noisy-neighbor test; Define p95 targets; Document bottlenecks',
        'Targets met or issues raised',
      ),
      I(
        'H-06',
        'Monitoring, alerting and dashboards',
        'infra',
        'P0',
        'M',
        'INF-01',
        'Per-tenant error rate and latency; Uptime checks and alerts; Cost budgets and alerts',
        'Alert fires in a drill',
      ),
      I(
        'H-07',
        'Backups and disaster recovery drill',
        'infra',
        'P0',
        'M',
        'INF-01',
        'Point-in-time recovery enabled; Restore test performed; RTO and RPO documented',
        'Restore proven in staging',
      ),
      I(
        'H-08',
        'Production infrastructure (IaC)',
        'infra',
        'P0',
        'L',
        'INF-01',
        'Prod environment with WAF, autoscaling, multi-zone and secrets; Region India',
        'Prod mirrors staging via IaC',
      ),
      I(
        'H-09',
        'CD pipeline with approvals and rollback',
        'infra',
        'P0',
        'M',
        'H-08',
        'Staging to prod promotion with approval; Migration handling; Rollback procedure tested',
        'Rollback rehearsed',
      ),
      I(
        'H-10',
        'Compliance checklist (DPDP, and HIPAA or GDPR if applicable)',
        'security',
        'P0',
        'M',
        'H-03',
        'Consent, retention and residency review; Breach response process; Audit log review; BAA if serving US customers',
        'Checklist signed off',
      ),
      I(
        'H-11',
        'Documentation and runbooks',
        'docs',
        'P1',
        'M',
        'H-09',
        'Architecture overview; Onboarding a hospital; Incident response and support access procedure',
        'A new engineer can run and deploy from the docs',
      ),
      I(
        'H-12',
        'Pilot hospital onboarding and feedback loop',
        'product',
        'P0',
        'M',
        'H-09 PL-07',
        'Onboard the pilot hospital; Collect feedback and triage into issues',
        'Pilot users active; feedback issues filed',
      ),
      I(
        'H-13',
        'Launch checklist and go/no-go',
        'product',
        'P0',
        'S',
        'H-12',
        'Review exit criteria for every milestone; Confirm monitoring, backups and support readiness',
        'Go/no-go recorded',
      ),
    ],
  },
  {
    key: 'BL',
    title: 'Backlog',
    weeks: 0,
    goal: 'Ideas and future features. Not scheduled.',
    exit: 'Promote to a milestone when decided.',
    refs: 'Adding a new feature later',
    issues: [
      I(
        'FUT-01',
        'Appointment reminders (email, SMS, WhatsApp)',
        'product',
        'P2',
        'L',
        '',
        'Build as a feature module per the worked example in CLAUDE.md; Consent check, templates, quota, opt-out; Provider adapters',
        'Added with no core changes',
        { extra: ['status:needs-decision'] },
      ),
      I(
        'FUT-02',
        'Per-hospital SSO (OIDC and SAML)',
        'backend',
        'P2',
        'L',
        '',
        'Evaluate Keycloak or Zitadel; Per-tenant identity provider settings; Email-based discovery at login',
        'A pilot hospital signs in with SSO',
        { extra: ['status:needs-decision'] },
      ),
      I(
        'FUT-03',
        'Custom domain per hospital',
        'product',
        'P2',
        'M',
        '',
        'Decide whether needed; DNS and certificate automation',
        'Decision recorded',
        { extra: ['status:needs-decision'] },
      ),
      I(
        'FUT-05',
        'ABDM and ABHA integration',
        'backend',
        'P2',
        'L',
        '',
        'Evaluate national health ID and record exchange requirements; Adapter design',
        'Scoped and estimated',
        { extra: ['status:needs-decision'] },
      ),
      I(
        'FUT-06',
        'HL7 or FHIR, lab analyzer and PACS integration adapters',
        'backend',
        'P2',
        'L',
        '',
        'Adapter interfaces for analyzers and imaging; FHIR resource mapping for patient, encounter and results',
        'Scoped and estimated',
        { extra: ['status:needs-decision'] },
      ),
      I(
        'FUT-07',
        'Telemedicine and patient-facing app',
        'product',
        'P2',
        'L',
        '',
        'Decide whether in scope (conflicts with the staff-only rule); Define consent and security model',
        'Decision recorded',
        { extra: ['status:needs-decision'] },
      ),
      I(
        'FUT-08',
        'Accounting export and statutory reports',
        'backend',
        'P2',
        'M',
        '',
        'Export to accounting software; Regional statutory report formats',
        'Scoped with pilot hospitals',
        { extra: ['status:needs-decision'] },
      ),
      I(
        'FUT-04',
        'Dedicated database for large hospitals',
        'infra',
        'P2',
        'L',
        '',
        'Routing layer for tenant to database; Migration of a tenant between databases',
        'Tenant moved with no downtime in staging',
        { extra: ['status:needs-decision'] },
      ),
    ],
  },
];

import {
  extraMilestones,
  appended,
  patches,
  nameOverrides,
  weeksOverrides,
  order,
  coreRelease,
} from './roadmap-extra.mjs';

const L2 = (x) =>
  x
    .split(';')
    .map((t) => t.trim())
    .filter(Boolean);
const allCore = Object.fromEntries(core.map((m) => [m.key, { ...m, issues: [...m.issues] }]));
for (const [k, list] of Object.entries(appended)) allCore[k].issues.push(...list);
for (const [k, w] of Object.entries(weeksOverrides)) allCore[k].weeks = w;
for (const [k, n] of Object.entries(nameOverrides)) allCore[k].name = n;
for (const m of Object.values(allCore)) {
  m.name = m.name ?? m.title.replace(/^M\d+\s+/, '');
  m.release = coreRelease[m.key] ?? '';
}
const byKey = { ...allCore, ...Object.fromEntries(extraMilestones.map((m) => [m.key, m])) };

const issueIndex = {};
for (const m of Object.values(byKey)) for (const i of m.issues) issueIndex[i.id] = i;
for (const [id, field, from, to] of patches) {
  const i = issueIndex[id];
  if (!i) throw new Error(`patch target missing: ${id}`);
  if (field === 'title') {
    if (i.title !== from) throw new Error(`patch mismatch ${id} title`);
    i.title = to;
  } else if (field === 'deps') {
    const idx = i.deps.indexOf(from);
    if (idx < 0) throw new Error(`patch mismatch ${id} deps`);
    i.deps.splice(idx, 1, ...to.split(' '));
  } else {
    const idx = i[field].indexOf(from);
    if (idx < 0) throw new Error(`patch mismatch ${id} ${field}: ${from}`);
    i[field].splice(idx, 1, ...L2(to));
  }
}

let n = 0;
export const milestones = order.map((k) => {
  const m = byKey[k];
  if (!m) throw new Error(`unknown milestone ${k}`);
  if (k === 'BL') return { ...m, key: 'BL', title: 'Backlog', name: 'Backlog' };
  const key = `M${n}`;
  const title = `${key} ${m.name}`;
  n++;
  return { ...m, key, title };
});

export const typeOf = (i) =>
  i.type ?? (/^(S-|INF-|H-|DS-06|IN-07|OP-07)/.test(i.id) ? 'chore' : 'feature');
export const flatIssues = () =>
  milestones.flatMap((m) =>
    m.issues.map((i) => ({ ...i, milestone: m.title, mkey: m.key, release: m.release })),
  );
